'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { fetchUserRole, type SessionUser } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import { LogoutButton } from '../logout-button';

type Vendor = { id: string; name: string; company?: string | null; email?: string | null; phone?: string | null; service_type?: string | null; notes?: string | null };
export default function VendorsPage() {
  const router = useRouter(); const [session, setSession] = useState<SessionUser | null>(null); const [vendors, setVendors] = useState<Vendor[]>([]); const [draft, setDraft] = useState({ name: '', company: '', email: '', phone: '', service_type: '', notes: '' }); const [error, setError] = useState<string | null>(null);
  useEffect(() => { void (async () => { const auth = await supabase?.auth.getSession(); const user = auth?.data.session?.user; if (!user) return router.replace('/login'); const role = await fetchUserRole(user.email, supabase); if (role === 'tenant') return router.replace('/dashboard'); setSession({ id: user.id, name: user.user_metadata?.full_name || user.email || 'User', email: user.email || '', role }); const response = await fetch('/api/vendors', { headers: { Authorization: `Bearer ${auth.data.session?.access_token}` } }); const result = await response.json(); if (!response.ok) setError(result.error); else setVendors(result.vendors ?? []); })(); }, [router]);
  const addVendor = async (event: React.FormEvent) => { event.preventDefault(); const token = (await supabase?.auth.getSession())?.data.session?.access_token; const response = await fetch('/api/vendors', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${token}` }, body: JSON.stringify(draft) }); const result = await response.json(); if (!response.ok) return setError(result.error); setVendors((current) => [...current, result.vendor]); setDraft({ name: '', company: '', email: '', phone: '', service_type: '', notes: '' }); };
  const removeVendor = async (id: string) => { if (!window.confirm('Remove this approved vendor?')) return; const token = (await supabase?.auth.getSession())?.data.session?.access_token; await fetch(`/api/vendors?id=${id}`, { method: 'DELETE', headers: { Authorization: `Bearer ${token}` } }); setVendors((current) => current.filter((vendor) => vendor.id !== id)); };
  if (!session) return null;
  return <main className="min-h-screen bg-slate-100 px-6 py-10 text-slate-900"><div className="mx-auto max-w-5xl"><header className="mb-8 flex flex-wrap items-center justify-between gap-3"><div><button type="button" onClick={() => router.push('/dashboard')} className="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Maintenance Tickets</button><h1 className="mt-2 text-3xl font-semibold">Approved Vendors</h1></div><LogoutButton /></header>{error && <div className="mb-5 rounded-xl bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<form onSubmit={addVendor} className="grid gap-3 rounded-2xl border border-slate-200 bg-white p-5 sm:grid-cols-3"><input required placeholder="Vendor name" value={draft.name} onChange={(e) => setDraft({ ...draft, name: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/><input placeholder="Company" value={draft.company} onChange={(e) => setDraft({ ...draft, company: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/><input placeholder="Service type" value={draft.service_type} onChange={(e) => setDraft({ ...draft, service_type: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/><input type="email" placeholder="Email" value={draft.email} onChange={(e) => setDraft({ ...draft, email: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/><input placeholder="Phone" value={draft.phone} onChange={(e) => setDraft({ ...draft, phone: e.target.value })} className="rounded-xl border border-slate-300 px-3 py-2 text-sm"/><button className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-medium text-white">Add vendor</button></form><div className="mt-6 grid gap-4 sm:grid-cols-2">{vendors.map((vendor) => <div key={vendor.id} className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><h2 className="font-semibold">{vendor.name}</h2><p className="text-sm text-slate-500">{vendor.company || vendor.service_type}</p></div><button type="button" onClick={() => void removeVendor(vendor.id)} className="text-xs text-rose-700">Remove</button></div>{vendor.email && <a className="mt-3 block text-sm underline" href={`mailto:${vendor.email}`}>{vendor.email}</a>}{vendor.phone && <a className="block text-sm underline" href={`tel:${vendor.phone}`}>{vendor.phone}</a>}</div>)}</div></div></main>;
}
